// Generated by Copilot
// Integration test for Connection struct

use neat_rust::architecture::connection::Connection;

#[test]
fn test_connection_new() {
    let conn = Connection::new(Some(1), Some(2), Some(0.5));
    assert_eq!(conn.from, Some(1));
    assert_eq!(conn.to, Some(2));
    assert_eq!(conn.weight, 0.5);
}

#[test]
fn test_connection_new_self() {
    let conn = Connection::new_self();
    assert_eq!(conn.weight, 0.0);
}
