// Generated by Copilot
// Integration test for Layer struct

use neat_rust::architecture::layer::Layer;

#[test]
fn test_layer_new() {
    let layer = Layer::new(3);
    assert_eq!(layer.size, 3);
}
