// Generated by Copilot
// Integration test for Network struct

use neat_rust::architecture::network::Network;

#[test]
fn test_network_new() {
    let net = Network::new(2, 1);
    assert_eq!(net.input, 2);
    assert_eq!(net.output, 1);
}
