// Generated by Copilot
// Integration test for Node struct

use neat_rust::architecture::node::Node;

#[test]
fn test_node_new() {
    let node = Node::new(Some("input"));
    assert_eq!(node.node_type, "input");
    assert_eq!(node.bias, 0.0);
}

#[test]
fn test_node_default_type() {
    let node = Node::new(None);
    assert_eq!(node.node_type, "hidden");
}
