// Generated by Copilot
// Integration test for NEAT-RS: test perceptron creation

use neat_rust::architecture::architect::Architect;

#[test]
fn test_perceptron_creation() {
    let net = Architect::perceptron(&[2, 3, 1]);
    assert_eq!(net.input, 2);
    assert_eq!(net.output, 1);
}
